CREATE ROLE DB_CONNECT;

GRANT CONNECT, RESOURCE, CREATE SESSION TO DB_CONNECT;
GRANT CREATE TRIGGER TO "DB_CONNECT" ;
GRANT CREATE VIEW TO "DB_CONNECT" ;
GRANT CREATE TABLE TO "DB_CONNECT" ;
GRANT CREATE TYPE TO "DB_CONNECT" ;
GRANT CREATE SYNONYM TO "DB_CONNECT" ;
GRANT CREATE SEQUENCE TO "DB_CONNECT" ;
GRANT CREATE USER TO "DB_CONNECT" ;
GRANT CREATE PROCEDURE TO "DB_CONNECT" ;
GRANT CREATE MATERIALIZED VIEW TO DB_CONNECT;
GRANT ALTER ANY MATERIALIZED VIEW TO DB_CONNECT;
GRANT CREATE JOB TO DB_CONNECT;
GRANT MANAGE SCHEDULER TO DB_CONNECT;
GRANT ALTER ANY SEQUENCE TO DB_CONNECT;
GRANT CREATE ANY SEQUENCE TO DB_CONNECT;
GRANT CREATE DATABASE LINK TO DB_CONNECT;

GRANT EXECUTE ON SYS.DBMS_ADVANCED_REWRITE TO DB_CONNECT;

--ALTER ROLE "DB_CONNECT" QUOTA UNLIMITED ON "SYSTEM";
--ALTER ROLE "DB_CONNECT" QUOTA UNLIMITED ON "USERS";

--SELECT * FROM DBA_ROLE_PRIVS WHERE ROLE = 'DB_CONNECT';

--SELECT * FROM DBA_ROLES WHERE ROLE = 'DB_CONNECT';

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'DB_CONNECT';

COMMIT;